<?php

namespace Database\Seeders;

use App\Models\CcdEntry;
use App\Models\DocumentarySeries;
use App\Models\DocumentarySubseries;
use App\Models\OrganizationalUnit;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class CcdSeeder extends Seeder
{
    public function run(): void
    {
        // ========================================================
        // 1. SERIES DOCUMENTALES (96 series del CCD)
        // ========================================================
        $seriesData = [
            ['01', 'Actas'],
            ['02', 'Actos administrativos'],
            ['03', 'Transferencias documentales'],
            ['04', 'Acciones constitucionales'],
            ['05', 'Acciones administrativas'],
            ['06', 'Comité de conciliación y defensa judicial'],
            ['07', 'Conceptos jurídicos'],
            ['08', 'Circulares'],
            ['09', 'Comunicaciones oficiales'],
            ['10', 'Informes a entes de control'],
            ['11', 'Informes institucionales'],
            ['12', 'Inventarios documentales'],
            ['13', 'Derechos de petición'],
            ['14', 'Atención ciudadana'],
            ['15', 'Gestión documental'],
            ['16', 'Preservación digital'],
            ['17', 'Gestión del riesgo'],
            ['18', 'Transparencia'],
            ['19', 'Rendición de cuentas'],
            ['20', 'Control institucional'],
            ['21', 'Informes de gestión'],
            ['22', 'Procesos administrativos coactivos'],
            ['23', 'Procesos administrativos sancionatorios'],
            ['24', 'Procesos jurídicos ejecutivos'],
            ['25', 'Procesos jurídicos ordinarios laborales'],
            ['26', 'Procesos disciplinarios'],
            ['27', 'Actuaciones judiciales'],
            ['28', 'Control disciplinario y contractual'],
            ['29', 'Talento humano'],
            ['30', 'Contratación'],
            ['31', 'Comunicaciones institucionales'],
            ['32', 'MIPG'],
            ['33', 'Planeación administrativa'],
            ['34', 'Dirección y coordinación'],
            ['35', 'Planeación del control'],
            ['36', 'Auditoría interna'],
            ['37', 'Evaluación institucional'],
            ['38', 'Seguimiento y control'],
            ['39', 'Austeridad del gasto'],
            ['40', 'Dirección fiscal y financiera'],
            ['41', 'Presupuesto'],
            ['42', 'Planeación financiera'],
            ['43', 'Contabilidad pública'],
            ['44', 'Tesorería'],
            ['45', 'Gestión tributaria'],
            ['46', 'Cobro coactivo'],
            ['47', 'Crédito público'],
            ['48', 'Control fiscal'],
            ['49', 'Planeación institucional'],
            ['50', 'Seguimiento y evaluación'],
            ['51', 'Banco de proyectos'],
            ['52', 'Estratificación socioeconómica'],
            ['53', 'Conceptos técnicos'],
            ['54', 'Asistencia técnica'],
            ['55', 'Planeación de infraestructura'],
            ['56', 'Estudios y diseños técnicos'],
            ['57', 'Ejecución de obras'],
            ['58', 'Supervisión e interventoría'],
            ['59', 'Mantenimiento institucional'],
            ['60', 'Salud pública'],
            ['61', 'Programas sociales'],
            ['62', 'Poblaciones vulnerables'],
            ['63', 'Cultura y patrimonio'],
            ['64', 'Educación'],
            ['65', 'SISBÉN'],
            ['66', 'Bienes sociales'],
            ['67', 'Programas poblacionales'],
            ['68', 'Procesos electorales'],
            ['69', 'Permisos y autorizaciones'],
            ['70', 'Certificaciones'],
            ['71', 'Policía administrativa'],
            ['72', 'Convivencia ciudadana'],
            ['73', 'Comisarías de familia'],
            ['74', 'Registro civil especial'],
            ['75', 'Operativos de tránsito'],
            ['76', 'Vehículos inmovilizados'],
            ['77', 'Comparendos'],
            ['78', 'Procesos contravencionales'],
            ['79', 'Registro de trámites de tránsito'],
            ['80', 'Registro de licencias de conducción'],
            ['81', 'Registro de vehículos'],
            ['82', 'Trámites de licencias'],
            ['83', 'Trámites de matrícula de vehículos'],
            ['84', 'Certificaciones de tránsito'],
            ['85', 'Informes de gestión de trámites'],
            ['86', 'Planeación agropecuaria'],
            ['87', 'Asistencia técnica agropecuaria'],
            ['88', 'Estudios agroambientales'],
            ['89', 'Certificaciones rurales'],
            ['90', 'Proyectos productivos'],
            ['91', 'Almacén y bienes'],
            ['92', 'Tecnologías de la información'],
            ['93', 'Gestión contractual'],
            ['94', 'Acciones judiciales'],
            ['95', 'Atención al ciudadano'],
            ['96', 'Control normativo'],
        ];

        $seriesMap = []; // code => id
        foreach ($seriesData as [$code, $name]) {
            $series = DocumentarySeries::firstOrCreate(
                ['code' => $code, 'name' => $name, 'is_active' => true],
                ['is_active' => true]
            );
            // Ensure it's active
            if (!$series->is_active) {
                $series->update(['is_active' => true]);
            }
            $seriesMap[$code] = $series->id;
        }

        $this->command->info('Created ' . count($seriesMap) . ' documentary series.');

        // ========================================================
        // 2. SUBSERIES DOCUMENTALES (del CCD)
        // ========================================================
        $subseriesData = [
            // [series_code, subseries_code, name]
            ['01', '01', 'Actas de Junta de Gobierno'],
            ['02', '01', 'Decretos'],
            ['02', '02', 'Resoluciones'],
            ['04', '01', 'Acciones de tutela'],
            ['04', '02', 'Acciones de cumplimiento'],
            ['04', '03', 'Acciones populares'],
            ['05', '01', 'Acción de repetición'],
            ['05', '02', 'Controversias contractuales'],
            ['05', '03', 'Nulidad'],
            ['05', '04', 'Nulidad y restablecimiento del derecho'],
            ['05', '05', 'Reparación directa'],
            ['05', '06', 'Observación de acuerdos municipales'],
            ['09', '01', 'Oficios'],
            ['09', '02', 'Internas'],
            ['11', '01', 'Informes a entes de control'],
            ['11', '02', 'Informes de gestión'],
            ['11', '03', 'Informes urbanísticos'],
            ['14', '01', 'Quejas, sugerencias y reclamos'],
            ['15', '01', 'Plan Institucional de Archivos – PINAR'],
            ['15', '02', 'Programa de Gestión Documental – PGD'],
            ['15', '03', 'Sistema Integrado de Conservación – SIC'],
            ['15', '04', 'Cuadro de Clasificación Documental – CCD'],
            ['15', '05', 'Tablas de Retención Documental – TRD'],
            ['15', '06', 'Tablas de Valoración Documental – TVD'],
            ['15', '07', 'Inventarios documentales (FUID)'],
            ['15', '08', 'Actas de transferencia documental'],
            ['15', '09', 'Actas de eliminación documental'],
            ['15', '10', 'Banco terminológico'],
            ['15', '11', 'Registro de préstamos y consultas'],
            ['16', '01', 'Preservación digital a largo plazo'],
            ['17', '01', 'Riesgos de corrupción'],
            ['17', '02', 'Plan municipal de gestión del riesgo'],
            ['17', '03', 'Ayudas humanitarias'],
            ['17', '04', 'Reportes de atención'],
            ['18', '01', 'Seguimiento ley de transparencia'],
            ['18', '02', 'Seguimiento SUIT'],
            ['19', '01', 'Rendición de cuenta fiscal'],
            ['20', '01', 'Informes a entes de control'],
            ['20', '02', 'Informes de gestión'],
            ['22', '01', 'Cuotas partes pensionales'],
            ['23', '01', 'Contractuales'],
            ['27', '01', 'Despachos comisorios'],
            ['27', '02', 'Embargos'],
            ['27', '03', 'Secuestros'],
            ['27', '04', 'Restituciones'],
            ['28', '01', 'Informes procesos disciplinarios'],
            ['28', '02', 'Seguimiento contratos y convenios'],
            ['29', '01', 'Historias laborales'],
            ['29', '02', 'Evaluación del desempeño'],
            ['29', '03', 'Comité de convivencia laboral'],
            ['29', '04', 'Comisión de personal'],
            ['29', '05', 'COPASST'],
            ['29', '06', 'Programas de bienestar social'],
            ['29', '07', 'Seguridad y salud en el trabajo – SG-SST'],
            ['29', '08', 'Cuotas partes pensionales'],
            ['30', '01', 'Contratos'],
            ['30', '02', 'Convenios interadministrativos'],
            ['30', '03', 'Procesos contractuales desiertos'],
            ['30', '04', 'Actas del comité de contratación'],
            ['31', '01', 'Plan de comunicaciones'],
            ['31', '02', 'Manual de imagen corporativa'],
            ['32', '01', 'Informes trimestrales MIPG'],
            ['33', '01', 'Plan de acción'],
            ['33', '02', 'Informes de gestión'],
            ['34', '01', 'Consejo de Gobierno'],
            ['34', '02', 'Comité de orden público'],
            ['34', '03', 'Comité de derechos humanos y paz'],
            ['34', '04', 'Comité cívico de convivencia'],
            ['34', '05', 'Comité de trabajo infantil'],
            ['34', '06', 'Comité institucional de gestión y desempeño'],
            ['34', '07', 'Consejo municipal de ciencia, tecnología e innovación'],
            ['34', '08', 'Comité de política social'],
            ['34', '09', 'Actas de empalme'],
            ['34', '10', 'Políticas institucionales'],
            ['35', '01', 'Plan anual de auditoría'],
            ['36', '01', 'Actas de auditoría'],
            ['36', '02', 'Informes de ejecución de auditoría'],
            ['37', '01', 'Evaluación institucional por dependencias'],
            ['37', '02', 'Evaluación sistema control interno contable'],
            ['37', '03', 'Evaluación rendición de cuentas'],
            ['38', '01', 'Planes de mejoramiento institucional'],
            ['38', '02', 'Seguimiento planes de mejoramiento'],
            ['38', '03', 'Seguimiento contratos SECOP'],
            ['38', '04', 'Seguimiento comité de conciliación'],
            ['40', '01', 'CONDFIS'],
            ['40', '02', 'Comité de depuración contable'],
            ['40', '03', 'Comité NICSP'],
            ['41', '01', 'Manuales de presupuesto'],
            ['41', '02', 'Programas Anuales Mensualizados de Caja – PAC'],
            ['41', '03', 'Informes de ejecución presupuestal'],
            ['42', '01', 'Plan marco fiscal y financiero'],
            ['42', '02', 'Estudios de evaluación fiscal'],
            ['43', '01', 'Estados financieros'],
            ['43', '02', 'Libros mayor y auxiliares'],
            ['43', '03', 'Comprobantes contables de ingreso'],
            ['43', '04', 'Comprobantes contables de egreso'],
            ['44', '01', 'Boletines diarios de tesorería'],
            ['44', '02', 'Saldos de cuentas bancarias'],
            ['45', '01', 'Registro de contribuyentes'],
            ['45', '02', 'Declaraciones tributarias'],
            ['45', '03', 'Acuerdos de pago'],
            ['45', '04', 'Programas de control de rentas'],
            ['45', '05', 'Boletines de deudores morosos'],
            ['47', '01', 'Contratos de empréstito'],
            ['48', '01', 'Informes a entes de control'],
            ['48', '02', 'Informes al DNP'],
            ['49', '01', 'Plan de desarrollo municipal'],
            ['49', '02', 'Planes estratégicos institucionales'],
            ['49', '03', 'Planes de acción institucional'],
            ['49', '04', 'Plan anticorrupción y atención al ciudadano'],
            ['49', '05', 'Plan operativo anual de inversiones – POAI'],
            ['50', '01', 'Informes de seguimiento al plan de desarrollo'],
            ['50', '02', 'Manuales de seguimiento'],
            ['51', '01', 'Proyectos de inversión municipal'],
            ['51', '02', 'Proyectos de inversión departamental'],
            ['51', '03', 'Proyectos SGR'],
            ['53', '01', 'Conceptos de presupuesto'],
            ['54', '01', 'Programas de asistencia técnica'],
            ['55', '01', 'Plan departamental vial'],
            ['56', '01', 'Gasificación'],
            ['56', '02', 'Infraestructura vial'],
            ['56', '03', 'Electrificación'],
            ['57', '01', 'Proyectos de infraestructura'],
            ['57', '02', 'Proyectos de servicios públicos'],
            ['57', '03', 'Redes e instalaciones'],
            ['57', '04', 'Actas de obra'],
            ['58', '01', 'Actas de supervisión'],
            ['58', '02', 'Informes técnicos'],
            ['59', '01', 'Mantenimiento de bienes y equipos'],
            ['60', '01', 'Boletines epidemiológicos'],
            ['60', '02', 'Planes de acción en salud mental'],
            ['60', '03', 'Auditoría régimen subsidiado'],
            ['60', '04', 'Control de enfermedades transmitidas por vectores'],
            ['61', '01', 'Colombia Mayor'],
            ['61', '02', 'Renta Ciudadana'],
            ['61', '03', 'Novedades de beneficiarios'],
            ['62', '01', 'Adulto mayor'],
            ['62', '02', 'Discapacidad'],
            ['62', '03', 'Prevención violencia sexual'],
            ['63', '01', 'Consejo municipal de cultura'],
            ['63', '02', 'Consejo de patrimonio cultural'],
            ['63', '03', 'Inventarios culturales'],
            ['63', '04', 'Programas culturales'],
            ['64', '01', 'Plan sectorial de educación'],
            ['64', '02', 'Programas educativos'],
            ['64', '03', 'PEI'],
            ['64', '04', 'Cobertura educativa'],
            ['64', '05', 'Planes de mejoramiento'],
            ['65', '01', 'Certificaciones'],
            ['65', '02', 'Novedades'],
            ['65', '03', 'Sistemas de información DNP'],
            ['66', '01', 'Donaciones'],
            ['66', '02', 'Inventarios de bienes'],
            ['67', '01', 'Comunidades étnicas'],
            ['67', '02', 'Erradicación del trabajo infantil'],
            ['68', '01', 'Comisión de seguimiento electoral'],
            ['68', '02', 'Instrumentos de control electoral'],
            ['69', '01', 'Espectáculos públicos'],
            ['69', '02', 'Extensión de horarios'],
            ['69', '03', 'Rifas'],
            ['69', '04', 'Ventas'],
            ['69', '05', 'Perifoneo'],
            ['70', '01', 'Certificados de residencia'],
            ['70', '02', 'Certificados de seguridad'],
            ['70', '03', 'Certificados de Territorialidad'],
            ['71', '01', 'Querellas civiles policivas'],
            ['71', '02', 'Procesos civiles de policía'],
            ['71', '03', 'Infracción decretos municipales'],
            ['71', '04', 'Infracción urbanística'],
            ['72', '01', 'Boletas de citación'],
            ['72', '02', 'Actas de compromiso'],
            ['72', '03', 'Actas de conciliación'],
            ['72', '04', 'Resoluciones policivas'],
            ['73', '01', 'Restablecimiento de derechos'],
            ['73', '02', 'Violencia intrafamiliar'],
            ['73', '03', 'Cuota alimentaria'],
            ['73', '04', 'Inasistencia alimentaria'],
            ['73', '05', 'Procesos ejecutivos de alimentos'],
            ['74', '01', 'Licencias de inhumación'],
            ['75', '01', 'Informes operativos de tránsito'],
            ['75', '02', 'Operativos de control vial'],
            ['75', '03', 'Puestos de control'],
            ['76', '01', 'Registro de vehículos inmovilizados'],
            ['78', '01', 'Recursos de reposición y apelación'],
            ['78', '02', 'Fallos contravencionales'],
            ['78', '03', 'Informes de procesos sancionatorios'],
            ['78', '04', 'Correspondencia asociada a procesos'],
            ['86', '01', 'Plan municipal de asistencia técnica'],
            ['86', '02', 'Programa municipal del sector agropecuario'],
            ['87', '01', 'Proyectos de asistencia técnica'],
            ['88', '01', 'Estudios agropecuarios'],
            ['88', '02', 'Estudios ambientales rurales'],
            ['89', '01', 'Fraccionamiento de predio'],
            ['89', '02', 'Pérdida de cultivo'],
            ['89', '03', 'Peritaje o valoración de cultivo'],
            ['91', '01', 'Comprobantes de ingreso'],
            ['91', '02', 'Comprobantes de egreso'],
            ['91', '03', 'Inventarios de activos fijos'],
            ['91', '04', 'Inventario general anual de bienes'],
            ['92', '01', 'Plan estratégico de TI'],
            ['92', '02', 'Licencias de software'],
            ['92', '03', 'Seguridad digital'],
            ['93', '01', 'Contratos de prestación de servicios'],
            ['94', '01', 'Acciones de tutela'],
            ['95', '01', 'Derechos de petición'],
            ['96', '01', 'Verificación ley de cuotas'],
            ['96', '02', 'Derechos de autor software'],
            ['96', '03', 'Informes de ley'],
        ];

        // subseriesMap: "series_code.sub_code" => id
        $subseriesMap = [];
        foreach ($subseriesData as [$seriesCode, $subCode, $name]) {
            if (!isset($seriesMap[$seriesCode])) {
                $this->command->warn("Series code {$seriesCode} not found for subseries {$name}");
                continue;
            }
            $subseries = DocumentarySubseries::firstOrCreate(
                [
                    'code' => $subCode,
                    'name' => $name,
                    'documentary_series_id' => $seriesMap[$seriesCode],
                ],
                ['is_active' => true]
            );
            if (!$subseries->is_active) {
                $subseries->update(['is_active' => true]);
            }
            $subseriesMap["{$seriesCode}.{$subCode}"] = $subseries->id;
        }

        $this->command->info('Created ' . count($subseriesMap) . ' documentary subseries.');

        // ========================================================
        // 3. UNIDADES ORGANIZACIONALES (Dependencias del CCD)
        // Map CCD codes to existing organizational units by their current codes
        // ========================================================
        // [ccd_code, ccd_name, existing_unit_code (current DB code)]
        $unitsMapping = [
            ['100', 'Despacho del Alcalde', 'DA'],
            ['110', 'Secretaría General y de Servicios Administrativos', 'SGA'],
            ['120', 'Secretaría de Gobierno', 'SGCC'],
            ['130', 'Secretaría de Hacienda', 'SH'],
            ['140', 'Secretaría de Planeación', 'SP'],
            ['150', 'Secretaría de Obras Públicas', 'SOP'],
            ['160', 'Secretaría de Desarrollo Social y Comunitario', 'SDSC'],
            ['170', 'Oficina Asesora de Control Interno', 'CI'],
            ['180', 'UMATA', 'UMATA'],
            ['190', 'Inspección de Tránsito y Transporte', 'ITT'],
        ];

        $unitMap = []; // ccd_code => id
        foreach ($unitsMapping as [$ccdCode, $ccdName, $existingCode]) {
            $unit = OrganizationalUnit::where('code', $existingCode)->first();
            if ($unit) {
                // Update existing unit with CCD code and name
                $unit->update([
                    'code' => $ccdCode,
                    'name' => $ccdName,
                    'slug' => Str::slug($ccdName),
                    'is_active' => true,
                ]);
                $unitMap[$ccdCode] = $unit->id;
            } else {
                // Fallback: try finding by CCD code (in case seeder ran before)
                $unit = OrganizationalUnit::where('code', $ccdCode)->first();
                if ($unit) {
                    $unitMap[$ccdCode] = $unit->id;
                } else {
                    $this->command->warn("Organizational unit with code '{$existingCode}' not found. Skipping CCD code {$ccdCode}.");
                }
            }
        }

        $this->command->info('Mapped ' . count($unitMap) . ' organizational units to CCD codes.');

        // ========================================================
        // 4. ENTRADAS CCD (mapeo dependencia → serie → subserie)
        // ========================================================
        // Format: [unit_code, series_code, subseries_code or null]
        // null subseries_code means the series has no subseries for this unit
        $ccdEntries = [
            // === 100 - Despacho del Alcalde ===
            ['100', '01', '01'],
            ['100', '02', '01'],
            ['100', '02', '02'],
            ['100', '03', null],
            ['100', '04', '01'],
            ['100', '04', '02'],
            ['100', '04', '03'],
            ['100', '05', '01'],
            ['100', '05', '02'],
            ['100', '05', '03'],
            ['100', '05', '04'],
            ['100', '05', '05'],
            ['100', '05', '06'],
            ['100', '06', null],
            ['100', '07', null],
            ['100', '10', null],
            ['100', '12', null],
            ['100', '22', '01'],
            ['100', '23', '01'],
            ['100', '24', null],
            ['100', '25', null],

            // === 110 - Secretaría General ===
            ['110', '02', '02'],
            ['110', '03', null],
            ['110', '08', null],
            ['110', '09', '01'],
            ['110', '09', '02'],
            ['110', '12', null],
            ['110', '15', '01'],
            ['110', '15', '02'],
            ['110', '15', '03'],
            ['110', '15', '04'],
            ['110', '15', '05'],
            ['110', '15', '06'],
            ['110', '15', '07'],
            ['110', '15', '08'],
            ['110', '15', '09'],
            ['110', '15', '10'],
            ['110', '15', '11'],
            ['110', '16', '01'],
            ['110', '17', '01'],
            ['110', '29', '01'],
            ['110', '29', '02'],
            ['110', '29', '03'],
            ['110', '29', '04'],
            ['110', '29', '05'],
            ['110', '29', '06'],
            ['110', '29', '07'],
            ['110', '29', '08'],
            ['110', '30', '01'],
            ['110', '30', '02'],
            ['110', '30', '03'],
            ['110', '30', '04'],
            ['110', '31', '01'],
            ['110', '31', '02'],
            ['110', '33', '01'],
            ['110', '33', '02'],
            ['110', '59', '01'],
            ['110', '91', '01'],
            ['110', '91', '02'],
            ['110', '91', '03'],
            ['110', '91', '04'],
            ['110', '92', '01'],
            ['110', '92', '02'],
            ['110', '92', '03'],

            // === 120 - Secretaría de Gobierno ===
            ['120', '02', '02'],
            ['120', '03', null],
            ['120', '08', null],
            ['120', '09', '01'],
            ['120', '09', '02'],
            ['120', '11', '01'],
            ['120', '11', '02'],
            ['120', '11', '03'],
            ['120', '12', null],
            ['120', '13', null],
            ['120', '17', '02'],
            ['120', '17', '03'],
            ['120', '17', '04'],
            ['120', '26', null],
            ['120', '27', '01'],
            ['120', '27', '02'],
            ['120', '27', '03'],
            ['120', '27', '04'],
            ['120', '34', '01'],
            ['120', '34', '02'],
            ['120', '34', '03'],
            ['120', '34', '04'],
            ['120', '34', '05'],
            ['120', '67', '01'],
            ['120', '67', '02'],
            ['120', '68', '01'],
            ['120', '68', '02'],
            ['120', '69', '01'],
            ['120', '69', '02'],
            ['120', '69', '03'],
            ['120', '69', '04'],
            ['120', '69', '05'],
            ['120', '70', '01'],
            ['120', '70', '02'],
            ['120', '70', '03'],
            ['120', '71', '01'],
            ['120', '71', '02'],
            ['120', '71', '03'],
            ['120', '71', '04'],
            ['120', '72', '01'],
            ['120', '72', '02'],
            ['120', '72', '03'],
            ['120', '72', '04'],
            ['120', '73', '01'],
            ['120', '73', '02'],
            ['120', '73', '03'],
            ['120', '73', '04'],
            ['120', '73', '05'],
            ['120', '74', '01'],

            // === 130 - Secretaría de Hacienda ===
            ['130', '02', '02'],
            ['130', '03', null],
            ['130', '08', null],
            ['130', '12', null],
            ['130', '40', '01'],
            ['130', '40', '02'],
            ['130', '40', '03'],
            ['130', '41', '01'],
            ['130', '41', '02'],
            ['130', '41', '03'],
            ['130', '42', '01'],
            ['130', '42', '02'],
            ['130', '43', '01'],
            ['130', '43', '02'],
            ['130', '43', '03'],
            ['130', '43', '04'],
            ['130', '44', '01'],
            ['130', '44', '02'],
            ['130', '45', '01'],
            ['130', '45', '02'],
            ['130', '45', '03'],
            ['130', '45', '04'],
            ['130', '45', '05'],
            ['130', '46', null],
            ['130', '47', '01'],
            ['130', '48', '01'],
            ['130', '48', '02'],

            // === 140 - Secretaría de Planeación ===
            ['140', '02', '02'],
            ['140', '03', null],
            ['140', '08', null],
            ['140', '12', null],
            ['140', '20', '01'],
            ['140', '34', '06'],
            ['140', '34', '07'],
            ['140', '34', '08'],
            ['140', '49', '01'],
            ['140', '49', '02'],
            ['140', '49', '03'],
            ['140', '49', '04'],
            ['140', '49', '05'],
            ['140', '50', '01'],
            ['140', '50', '02'],
            ['140', '51', '01'],
            ['140', '51', '02'],
            ['140', '51', '03'],
            ['140', '52', null],
            ['140', '53', '01'],
            ['140', '54', '01'],
            ['140', '93', '01'],
            ['140', '94', '01'],

            // === 150 - Secretaría de Obras Públicas ===
            ['150', '02', '02'],
            ['150', '03', null],
            ['150', '08', null],
            ['150', '12', null],
            ['150', '20', '01'],
            ['150', '55', '01'],
            ['150', '56', '01'],
            ['150', '56', '02'],
            ['150', '56', '03'],
            ['150', '57', '01'],
            ['150', '57', '02'],
            ['150', '57', '03'],
            ['150', '57', '04'],
            ['150', '58', '01'],
            ['150', '58', '02'],

            // === 160 - Secretaría de Desarrollo Social y Comunitario ===
            ['160', '02', '02'],
            ['160', '03', null],
            ['160', '08', null],
            ['160', '12', null],
            ['160', '20', '01'],
            ['160', '20', '02'],
            ['160', '34', '09'],
            ['160', '34', '10'],
            ['160', '60', '01'],
            ['160', '60', '02'],
            ['160', '60', '03'],
            ['160', '60', '04'],
            ['160', '61', '01'],
            ['160', '61', '02'],
            ['160', '61', '03'],
            ['160', '62', '01'],
            ['160', '62', '02'],
            ['160', '62', '03'],
            ['160', '63', '01'],
            ['160', '63', '02'],
            ['160', '63', '03'],
            ['160', '63', '04'],
            ['160', '64', '01'],
            ['160', '64', '02'],
            ['160', '64', '03'],
            ['160', '64', '04'],
            ['160', '64', '05'],
            ['160', '65', '01'],
            ['160', '65', '02'],
            ['160', '65', '03'],
            ['160', '66', '01'],
            ['160', '66', '02'],
            ['160', '95', '01'],

            // === 170 - Control Interno ===
            ['170', '03', null],
            ['170', '08', null],
            ['170', '10', null],
            ['170', '12', null],
            ['170', '14', '01'],
            ['170', '18', '01'],
            ['170', '18', '02'],
            ['170', '19', '01'],
            ['170', '21', null],
            ['170', '28', '01'],
            ['170', '28', '02'],
            ['170', '32', '01'],
            ['170', '35', '01'],
            ['170', '36', '01'],
            ['170', '36', '02'],
            ['170', '37', '01'],
            ['170', '37', '02'],
            ['170', '37', '03'],
            ['170', '38', '01'],
            ['170', '38', '02'],
            ['170', '38', '03'],
            ['170', '38', '04'],
            ['170', '39', null],
            ['170', '96', '01'],
            ['170', '96', '02'],
            ['170', '96', '03'],

            // === 180 - UMATA ===
            ['180', '02', '02'],
            ['180', '03', null],
            ['180', '08', null],
            ['180', '12', null],
            ['180', '20', '01'],
            ['180', '20', '02'],
            ['180', '86', '01'],
            ['180', '86', '02'],
            ['180', '87', '01'],
            ['180', '88', '01'],
            ['180', '88', '02'],
            ['180', '89', '01'],
            ['180', '89', '02'],
            ['180', '89', '03'],
            ['180', '90', null],

            // === 190 - Inspección de Tránsito y Transporte ===
            ['190', '02', '02'],
            ['190', '03', null],
            ['190', '08', null],
            ['190', '12', null],
            ['190', '75', '01'],
            ['190', '75', '02'],
            ['190', '75', '03'],
            ['190', '76', '01'],
            ['190', '77', null],
            ['190', '78', '01'],
            ['190', '78', '02'],
            ['190', '78', '03'],
            ['190', '78', '04'],
            ['190', '79', null],
            ['190', '80', null],
            ['190', '81', null],
            ['190', '82', null],
            ['190', '83', null],
            ['190', '84', null],
            ['190', '85', null],
        ];

        $entryCount = 0;
        foreach ($ccdEntries as [$unitCode, $seriesCode, $subCode]) {
            if (!isset($unitMap[$unitCode])) {
                $this->command->warn("Unit {$unitCode} not found");
                continue;
            }
            if (!isset($seriesMap[$seriesCode])) {
                $this->command->warn("Series {$seriesCode} not found for unit {$unitCode}");
                continue;
            }

            $subseriesId = null;
            if ($subCode !== null) {
                $key = "{$seriesCode}.{$subCode}";
                if (!isset($subseriesMap[$key])) {
                    $this->command->warn("Subseries {$key} not found for unit {$unitCode}");
                    continue;
                }
                $subseriesId = $subseriesMap[$key];
            }

            CcdEntry::firstOrCreate([
                'organizational_unit_id' => $unitMap[$unitCode],
                'documentary_series_id' => $seriesMap[$seriesCode],
                'documentary_subseries_id' => $subseriesId,
            ]);
            $entryCount++;
        }

        $this->command->info("Created {$entryCount} CCD entries.");
    }
}
